### ISSUE TITLE
IDE Path Sets wrong

### ISSUE THREAD

**Issue by VojkoCendak** [DelphiWorlds/Codex#23]
Don't know if that is intended, but the default paths are not equal to actual path in Tools->Options->Language->Delphi->Library->Library Path.

**Comment by DelphiWorlds** [comment]
It is intended that way - IDE Path Sets changes the values in Tools->Options->Language->Delphi->Library->Library Path based on what sets you have enabled. Otherwise, it wouldn't work :-)

**Comment by DelphiWorlds** [comment]
I'm considering removing this feature, or changing it significantly, because installing components that alter the IDE paths can cause problems

**Comment by DelphiWorlds** [comment]
This feature will be removed in 1.6.0, and will be re-thought out
