### ISSUE TITLE
[Internal] Remove dependence on JCL/JVCL

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/Codex#26]
As per the title, internally Codex is dependent on JCL/JVCL, specifically for executing processes such as some of the build tool executables for Android. This is the *only* part required by Codex, so it would be a "nice to have" to remove it.

The code to do this is currently not working, and a [demo has been set up in Playground](https://github.com/DelphiWorlds/Playground/tree/main/Demos/RunProcess) to seek help

**Comment by War3Evo** [comment]
Your "Create Process" is a bit complex for just executing commands in cmd.  Do you really need it that complex in order to execute command prompt stuff?

Try doing it via my component: https://github.com/War3Evo/gtDelphi/blob/master/CommandPrompt/gtCommandPrompt.pas

**Comment by DelphiWorlds** [comment]
"Your "Create Process" is a bit complex for just executing commands in cmd."
It's not my code - it's from JVCL, and yes, it is a bit of overkill, which is one of the reasons why I wanted to remove the dependency on JVCL. I now have an alternative, as per my reply in the discussions section.
