### ISSUE TITLE
Uninstall method

### ISSUE THREAD

**Issue by bdwilton** [DelphiWorlds/Codex#30]
Hey,
Just been having a quick test and play.
I couldn't see in the documentation (may have missed it) but what is the best method for uninstalling ?
I was getting an Access Violation on shutdown in BDS (image belopw) after installing so was going to verify it was the Codex that caused that or not.
This is a new setup in 11.3 so Codex 1.6 and I hadn't setup either Android or IOS compilers before installing.
I just now installed IOS Compiler but are still getting the BDS.exe AV on shutdown. 
![Capture1](https://user-images.githubusercontent.com/11957093/231026590-e0a681d5-00e4-4db3-ac2a-88b033ee1d42.JPG)

**Comment by DelphiWorlds** [comment]
There should be an uninstaller in C:\Program Files (x86)\DelphiWorlds\Codex

..and yes, it may well be Codex causing the AV on shutdown. I'm looking into it.

**Comment by bdwilton** [comment]
Thanks, yes I can confirm the un-install seems to have stopped that AV.

**Comment by DelphiWorlds** [comment]
Trouble is: it doesn't always happen for me, so it has been a bit hard to track down
