### ISSUE TITLE
Package Download -Cannot Find Package

### ISSUE THREAD

**Issue by bo3l4q** [DelphiWorlds/Codex#40]
![image](https://github.com/user-attachments/assets/26347e36-2987-4d75-9ad8-707a19285fdb)

**Comment by DelphiWorlds** [comment]
You don't search on the complete gradle short code. Try just biometric

**Comment by bo3l4q** [comment]
I've changed networks, the results are the same

![image](https://github.com/user-attachments/assets/64348f7e-269b-435f-9c0e-1007f3881385)

**Comment by DelphiWorlds** [comment]
Can you reach this URL in a browser on the same machine?: https://mvnrepository.com/

**Comment by bo3l4q** [comment]
yes.

![image](https://github.com/user-attachments/assets/1266df30-8d08-45d5-8617-501ef047b6b7)

**Comment by DelphiWorlds** [comment]
Can you try this one?
https://mvnrepository.com/search?q=biometric
If that link works in a browser, I'm not sure what the problem is. What version of Delphi and Codex are you using?

**Comment by bo3l4q** [comment]
![image](https://github.com/user-attachments/assets/68d337ad-6363-4307-b628-7e8799edcf5c)

**Comment by bo3l4q** [comment]
I tried with Delphi 12 Athens, the results are the same

**Comment by DelphiWorlds** [comment]
You still get the `Timed out` message? When you use a browser, does it take more than 30 seconds to get a response? If so, I may have to include an option to increase the timeout

**Comment by DelphiWorlds** [comment]
I've just realised that it is **already** possible to change the timeout, but you need to modify the `config.json` file in either: `Public Documents\Codex280` or `Public Documents\Codex290` (depending on Delphi 11.x or 12.x):

![image](https://github.com/user-attachments/assets/4c5c00ff-9451-4a07-a781-0ae3d6c45843)

..and restart Delphi

**Comment by bo3l4q** [comment]
I don't know where it went wrong, all the tricks you gave didn't work. Finally I tried reinstalling Windows 10, then I installed Delphi 11 Alexandria and Codex 2.3.2, the results were the same. I tried installing Delphi 12 Athens and Codex 2.3.2, the results were the same. I tried Codex 2.4, same result.

I installed Windows 11 ver 24H2 + Delphi 11 Alexandria + Delphi 12 Athens + Codex 2.3.2 + Codex 2.4, all the results are the same. So where did it go wrong?

Maybe if you have time, you can remote my computer.

**Comment by bo3l4q** [comment]
**Bug found.**

I downloaded the latest SourceCode Codex. When I Debug, it turns out TEdgeBrowser doesn't load "WebView2Loader.dll". I simply copy/pasted "WebView2Loader.dll" to: C:\Program Files (x86)\Embarcadero\Studio\23.0\bin.

Finished
