### ISSUE TITLE
i have installed DELPHI RIO 10.3 in Custom PATH

### ISSUE THREAD

**Issue by tuadmin** [DelphiWorlds/Codex#5]
![image](https://user-images.githubusercontent.com/795061/51159110-dbca3c80-185d-11e9-8e2d-395da20cb5e1.png)
and show , this error

**Comment by DelphiWorlds** [comment]
Sorry for the delay in an answer; I don't have notifications set for this as yet. This will be resolved in 1.2, to be released this week

**Comment by DelphiWorlds** [comment]
This should now be fixed in 1.2
