### ISSUE TITLE
"Android Tools Options" dialog shows white background on Dark Theme

### ISSUE THREAD

**Issue by alexdgs** [DelphiWorlds/Codex#6]
When Dark Theme is active on the IDE accessing to Tools -> Codex -> Android Tools -> Options shows a dialog with white background, making impossible to read the titles over the text fields and lists. On Light Theme the dialog shows correctly.
Additionally, when starting the IDE on Dark Theme, then switching to Light Theme and switching back to Dark Theme the dialog paints as if Light Theme is active.
Using Delphi Rio 10.3.3

![codex_android_options](https://user-images.githubusercontent.com/7460734/70645028-8851a180-1c1a-11ea-87d7-3c1bc4cf2096.png)

**Comment by DelphiWorlds** [comment]
This was fixed somewhere along the line :-)
