### ISSUE TITLE
run Device Lens on menu LogCat Viewer  

### ISSUE THREAD

**Issue by dshumko** [DelphiWorlds/Codex#8]
Run DeviceLens.exe if it is in the same directory as CodexXXX.dll or installed on the PC

**Comment by DelphiWorlds** [comment]
I don't understand your report. Is there an actual problem?

**Comment by dshumko** [comment]
this is not a problem, but an improvement

**Comment by dshumko** [comment]
Now the menu item leads to the site, but the Device Lens is already installed. Let's run it :)

**Comment by DelphiWorlds** [comment]
Ah, ok.. I understand now; thanks!

**Comment by DelphiWorlds** [comment]
Dang.. missed it for v1.3. I've earmarked it for 1.3.1

**Comment by DelphiWorlds** [comment]
Fixed by: https://github.com/DelphiWorlds/Codex/commit/5475cea2dbf437f7328f3efc1477bc0c7a4887a9
